[alias]
kernel = "build -p feox-xokernel --bin feox-xokernel --target x86_64-unknown-none"
loader = "build -p feox-loader-uefi --bin feox-loader-uefi --target x86_64-unknown-uefi"
kernel-arm = "build -p feox-xokernel --bin feox-xokernel --target aarch64-unknown-none-softfloat"
loader-arm = "build -p feox-loader-uefi --bin feox-loader-uefi --target aarch64-unknown-uefi"

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tkernel/feox-xokernel/linker.ld"]
